# Site settings
title: Home | Erik R. Rygg
name: Erik R. Rygg
description: DevOps enthusiast and practitioner, bourbon drinker, dog lover, and family man

avatar: https://avatars2.githubusercontent.com/u/1319170?s=400&u=118595ff64881edd04c8dcd9f44280e98558e7e9&v=4

footer-links:
  email: errygg@gmail.com
  facebook: erygg
  github: errygg
  instagram: errygg
  linkedin: errygg
  twitter: errygg

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  -jekyll-sitemap
  -jekyll-feed
  -jekyll-crossport-to-medium

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
