version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - run:
          name: Prepare shell commands
          command: cp scripts/deploy-ghpages.sh ../ && chmod 755 ../deploy-ghpages.sh
      - add_ssh_keys:
          fingerprints:
            - "9a:da:fc:53:78:df:53:89:dd:ca:35:94:e0:14:ea:43"
      - run:
          name: Run deploy scripts
          command: ../deploy-ghpages.sh
